//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: Provide convenient mapping for shader constants (C++ side).
//          The DX9 tree shares shader_constant_register_map.h between HLSL and C++; the native HLSL copy lives in
//          hlsl/common, so the C++ names are repeated here with their register numbers unchanged.
//
// $NoKeywords: $
//=============================================================================
#ifndef CPP_SHADER_CONSTANT_REGISTER_MAP_H
#define CPP_SHADER_CONSTANT_REGISTER_MAP_H

#define PSREG_SELFILLUMTINT						PSREG_CONSTANT_00
#define PSREG_DIFFUSE_MODULATION				PSREG_CONSTANT_01
#define PSREG_ENVMAP_TINT__SHADOW_TWEAKS		PSREG_CONSTANT_02
#define PSREG_SELFILLUM_SCALE_BIAS_EXP			PSREG_CONSTANT_03
#define PSREG_AMBIENT_CUBE						PSREG_CONSTANT_04
//		PSREG_AMBIENT_CUBE						PSREG_CONSTANT_05
//		PSREG_AMBIENT_CUBE						PSREG_CONSTANT_06
//		PSREG_AMBIENT_CUBE						PSREG_CONSTANT_07
//		PSREG_AMBIENT_CUBE						PSREG_CONSTANT_08
//		PSREG_AMBIENT_CUBE						PSREG_CONSTANT_09
#define PSREG_ENVMAP_FRESNEL__SELFILLUMMASK		PSREG_CONSTANT_10
#define PSREG_EYEPOS_SPEC_EXPONENT				PSREG_CONSTANT_11
#define PSREG_FOG_PARAMS						PSREG_CONSTANT_12
#define PSREG_FLASHLIGHT_ATTENUATION			PSREG_CONSTANT_13
#define PSREG_FLASHLIGHT_POSITION_RIM_BOOST		PSREG_CONSTANT_14
#define PSREG_FLASHLIGHT_TO_WORLD_TEXTURE		PSREG_CONSTANT_15
//		PSREG_FLASHLIGHT_TO_WORLD_TEXTURE		PSREG_CONSTANT_16
//		PSREG_FLASHLIGHT_TO_WORLD_TEXTURE		PSREG_CONSTANT_17
//		PSREG_FLASHLIGHT_TO_WORLD_TEXTURE		PSREG_CONSTANT_18
#define PSREG_FRESNEL_SPEC_PARAMS				PSREG_CONSTANT_19
#define PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_20
//		PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_21
//		PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_22
//		PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_23
//		PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_24
//		PSREG_LIGHT_INFO_ARRAY					PSREG_CONSTANT_25
#define PSREG_SPEC_RIM_PARAMS					PSREG_CONSTANT_26
// #define **free**								PSREG_CONSTANT_27	//actually using this often blows constant limits, since literals have to get stuffed somewhere...
#define	PSREG_FLASHLIGHT_COLOR					PSREG_CONSTANT_28
#define	PSREG_LINEAR_FOG_COLOR					PSREG_CONSTANT_29
#define	PSREG_LIGHT_SCALE						PSREG_CONSTANT_30
#define	PSREG_FLASHLIGHT_SCREEN_SCALE			PSREG_CONSTANT_31
//  --- End of ps_2_0 and ps_2_b constants ---

// For the C code, map the above file's defines back to integers...
#define PSREG_CONSTANT_00	0
#define PSREG_CONSTANT_01	1
#define PSREG_CONSTANT_02	2
#define PSREG_CONSTANT_03	3
#define PSREG_CONSTANT_04	4
#define PSREG_CONSTANT_05	5
#define PSREG_CONSTANT_06	6
#define PSREG_CONSTANT_07	7
#define PSREG_CONSTANT_08	8
#define PSREG_CONSTANT_09	9
#define PSREG_CONSTANT_10	10
#define PSREG_CONSTANT_11	11
#define PSREG_CONSTANT_12	12
#define PSREG_CONSTANT_13	13
#define PSREG_CONSTANT_14	14
#define PSREG_CONSTANT_15	15
#define PSREG_CONSTANT_16	16
#define PSREG_CONSTANT_17	17
#define PSREG_CONSTANT_18	18
#define PSREG_CONSTANT_19	19
#define PSREG_CONSTANT_20	20
#define PSREG_CONSTANT_21	21
#define PSREG_CONSTANT_22	22
#define PSREG_CONSTANT_23	23
#define PSREG_CONSTANT_24	24
#define PSREG_CONSTANT_25	25
#define PSREG_CONSTANT_26	26
#define PSREG_CONSTANT_27	27
#define PSREG_CONSTANT_28	28
#define PSREG_CONSTANT_29	29
#define PSREG_CONSTANT_30	30
#define PSREG_CONSTANT_31	31

#endif // CPP_SHADER_CONSTANT_REGISTER_MAP_H
