// DX12 native preamble shared by every native source (generated by gencommon.py): stage selection,
// backend-owned engine cbuffers, raster emulation and the typed texture/sampler pairs.
#ifndef DX12_PREAMBLE_H
#define DX12_PREAMBLE_H

// ---- DX12 native preamble (not in the legacy header) ----------------------------------------------------------
#if defined(DX12_LEGACY_VS20) || defined(DX12_LEGACY_VS30)
#define DX12_STAGE_VERTEX 1
#elif defined(DX12_LEGACY_PS20) || defined(DX12_LEGACY_PS20B) || defined(DX12_LEGACY_PS30)
#define DX12_STAGE_PIXEL 1
#else
#error Native sources must define exactly one DX12_LEGACY_{VS20,VS30,PS20,PS20B,PS30}
#endif
#include "dx12_engine_cbuffers.h"
#include "dx12_raster_emulation.h"
// Typed texture/sampler pairs replacing DX9 `sampler` objects; t<n>/s<n> keep the legacy sampler index.
struct DX12Sampler2D { Texture2D tex; SamplerState smp; };
struct DX12SamplerCube { TextureCube tex; SamplerState smp; };
struct DX12Sampler3D { Texture3D tex; SamplerState smp; };
// D3D9 has no 1D textures: sampler1D binds a 2D texture and tex1D replicates u (texld r, r.xxxx).
struct DX12Sampler1D { Texture2D tex; SamplerState smp; };
// Shadow depth maps: tex2Dproj is the D3D9 hardware compare (ref = z/w, LESS_EQUAL, filtered by the sampler);
// tex2D reads the stored depth (only non-PCF shadow modes, which the DX12 config never selects).
struct DX12ShadowSampler { Texture2D tex; SamplerComparisonState smp; };
float4 DX12ShadowCompareProj( DX12ShadowSampler s, float4 p ) { return s.tex.SampleCmpLevelZero( s.smp, p.xy / p.w, p.z / p.w ).xxxx; }
float4 DX12ShadowRaw( DX12ShadowSampler s, float2 uv )
{
	uint width, height;
	s.tex.GetDimensions( width, height );
	// Point read with clamp addressing (shadow depth textures are created clamped).
	return s.tex.Load( int3( clamp( int2( floor( uv * float2( width, height ) ) ), int2( 0, 0 ), int2( width, height ) - 1 ), 0 ) );
}
// A colour texture passed as the depth sampler (worldtwotextureblend binds its flashlight cookie there) has no
// comparison in D3D9 either: texldp/texld on a non-depth format are plain projective/regular samples. The shadow
// helpers have DX12Sampler2D overloads (common_flashlight_fxc.h) that end here.
float4 DX12ShadowCompareProj( DX12Sampler2D s, float4 p ) { return s.tex.Sample( s.smp, p.xy / p.w ); }
float4 DX12ShadowRaw( DX12Sampler2D s, float2 uv ) { return s.tex.Sample( s.smp, uv ); }
// D3D9 arithmetic edge cases the shipped VCS rely on (the DX12 legacy translator reproduces them in
// thirdparty/dx12_shaderconv context.cpp Translate_NRM/Translate_RSQ): rsq/nrm of 0 use FLT_MAX instead of +inf,
// so normalize(0) is 0 (not NaN) and rsqrt(0) is FLT_MAX. Native sources route normalize/rsqrt through these.
float DX12Rsq( float x ) { const float a = abs( x ); return a != 0.0f ? rsqrt( a ) : 3.402823466e+38f; }
float2 DX12Rsq( float2 x ) { return float2( DX12Rsq( x.x ), DX12Rsq( x.y ) ); }
float3 DX12Rsq( float3 x ) { return float3( DX12Rsq( x.x ), DX12Rsq( x.y ), DX12Rsq( x.z ) ); }
float4 DX12Rsq( float4 x ) { return float4( DX12Rsq( x.x ), DX12Rsq( x.y ), DX12Rsq( x.z ), DX12Rsq( x.w ) ); }
float2 DX12Normalize( float2 v ) { return v * DX12Rsq( dot( v, v ) ); }
float3 DX12Normalize( float3 v ) { return v * DX12Rsq( dot( v, v ) ); }
float4 DX12Normalize( float4 v ) { return v * DX12Rsq( dot( v, v ) ); }
#define normalize DX12Normalize
#define rsqrt DX12Rsq
// ---------------------------------------------------------------------------------------------------------------
#endif
