// Generated by gencommon.py; native raster behavior shared with early-depth twins.
#ifndef DX12_RASTER_EMULATION_H
#define DX12_RASTER_EMULATION_H
#include "dx12_engine_cbuffers.h"

#if defined(DX12_STAGE_VERTEX)
// vsconv.cpp:998-1029 corrects the original clip position for the DX9 viewport.
float4 DX12Position(float4 clipPosition)
{
    float4 corrected = clipPosition;
    corrected.xy = mad(cViewportScale.xy, clipPosition.ww, clipPosition.xy);
    return corrected;
}
struct DX12ClipDistances
{
    float4 first : SV_ClipDistance0;
    float2 second : SV_ClipDistance1;
};
DX12ClipDistances DX12UserClipDistances(float4 uncorrectedClipPosition)
{
    DX12ClipDistances result;
    [unroll] for (uint i = 0; i < 6; ++i)
    {
        float distance = ((cClipMask.x & (1u << i)) != 0u)
            ? dot(uncorrectedClipPosition, cClipPlanes[i]) : 1.0f;
        if (i < 4) result.first[i] = distance;
        else result.second[i - 4] = distance;
    }
    return result;
}
#endif

#if defined(DX12_STAGE_PIXEL)
// D3D9 compares unquantized output alpha against the state setter's 8-bit reference.
// Forced early depth is selected only with alpha test and effective A2C disabled.
// Remove the kill at preprocessing time, not through a runtime uniform branch.
void DX12AlphaTest(float alpha)
{
#if !defined(DX12_EARLY_DEPTH)
    if (cAlphaTest.x == 0.0f) return;
    int comparison = (int)cAlphaTest.y;
    float reference = cAlphaTest.z;
    bool passes = (comparison == 2 && alpha < reference) ||
                  (comparison == 3 && alpha == reference) ||
                  (comparison == 4 && alpha <= reference) ||
                  (comparison == 5 && alpha > reference) ||
                  (comparison == 6 && alpha != reference) ||
                  (comparison == 7 && alpha >= reference) ||
                  comparison == 8;
    if (!passes) discard;
#endif
}
float4 DX12RasterFog(float4 color, float vertexFogFactor)
{
    if (cRasterFogColor.w != 0.0f)
        color.rgb = mad(color.rgb - cRasterFogColor.rgb,
                        saturate(vertexFogFactor), cRasterFogColor.rgb);
    return color;
}
float DX12RasterPixelFogFactor(float fogIndex, uint fogMode)
{
    if (fogMode == 3u)
    {
        if (fogIndex >= cRasterFogParams.y) return 0.0f;
        if (cRasterFogParams.x >= fogIndex) return 1.0f;
        return (cRasterFogParams.y - fogIndex) * cRasterFogParams.z;
    }
    float d = fogIndex * cRasterFogParams.w;
    if (fogMode == 1u) return exp2(d * -1.44269504088896f);
    if (fogMode == 2u) return exp2(d * d * -1.44269504088896f);
    return 1.0f;
}
float4 DX12FinishPixel(float4 color, float vertexFog)
{
    DX12AlphaTest(color.a);
#if !defined(DX12_LEGACY_PS30)
    color = DX12RasterFog(color, vertexFog);
#endif
    return color;
}
#endif
#endif
